### ISSUE TITLE
Cannot put cave on "call" instruction 

### ISSUE THREAD

**Issue by LPVOIDDev** [Gabrola/QuickCave#1]
I know that obviously copying bytes of original **call** instruction requires recalculation of the original **call** instruction **destination address** based on our new **eip**
But it would be awesome to have it convert it automatically
I guess that is very possible, but would complicate the code further
This is more of a improvement hint rather than an issue

**Comment by Gabrola** [comment]
Yes, that would be very possible. I think in most cases you should be able to inject the code cave on the instruction immediately preceding the call instruction unless the result of that instruction is needed for some reason.
